name: Python application

on:
  push:
    branches: [ main ]
  pull\_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 bandit
    - name: Analysing the code with pylint and flake8
      run: |
        pylint \$(git ls-files '*.py')
        flake8 \$(git ls-files '*.py')
    - name: Security check with Bandit
      run: |
        bandit -r . -ll
